session_name: pe-ha
windows:
  - window_name: PE Bootstrap
    layout: tiled
    panes:
      - blank:
        focus: true
      - shell_command: vagrant ssh primary
        sleep_after: 2
      - vagrant ssh primary -c 'sudo tail -f /var/log/messages' 
      - vagrant ssh replica -c 'sudo tail -f /var/log/messages'
